/**
 * AUTO-GENERATED FILE — do not edit manually.
 * Generated by: npx tsx scripts/generate-swml-verbs.ts
 *
 * Provides TypeScript interface augmentation for all SWML verb methods
 * auto-installed on SwmlBuilder from schema.json.
 */

import type {
  AiSidecarConfig,
  AmazonBedrockConfig,
  AnswerConfig,
  BindDigitConfig,
  ClearDigitBindingsConfig,
  ConnectConfig,
  DetectMachineConfig,
  EchoConfig,
  EnterQueueConfig,
  ExecuteConfig,
  ExecuteRpcConfig,
  GotoConfig,
  HangupConfig,
  JoinConferenceConfig,
  JoinRoomConfig,
  LabelConfig,
  LiveTranscribeConfig,
  LiveTranslateConfig,
  PayConfig,
  PromptConfig,
  ReceiveFaxConfig,
  RecordCallConfig,
  RecordConfig,
  RequestConfig,
  SendDigitsConfig,
  SendFaxConfig,
  SendSmsConfig,
  SetCapabilitiesConfig,
  SetMetaConfig,
  SipReferConfig,
  StopRecordCallConfig,
  StopStreamConfig,
  StopTapConfig,
  StreamConfig,
  SwitchConfig,
  TapConfig,
  TranscribeConfig,
  TransferConfig,
  UserEventConfig,
} from './swml_verbs_generated.js';

export interface AiVerbConfig {
  /** Text prompt for the AI agent (mutually exclusive with prompt when using POM). */
  prompt?: string | Array<Record<string, unknown>>;
  /** Optional post-prompt text sent to the LLM after the conversation ends. */
  post_prompt?: string;
  /** URL to receive post-prompt status callbacks. */
  post_prompt_url?: string;
  /** SignalWire AI Gateway (SWAIG) configuration for custom function/tool definitions. */
  SWAIG?: Record<string, unknown>;
  /** Additional AI parameters passed through to the platform. */
  [key: string]: unknown;
}

export interface PlayVerbConfig {
  /** Single URL to play (mutually exclusive with urls). */
  url?: string;
  /** Array of URLs to play (mutually exclusive with url). */
  urls?: string[];
  /** Volume level for audio playback. Valid range -40 to 40. Default 0. */
  volume?: number;
  /** Voice name to use for text-to-speech (e.g. "Polly.Joanna"). */
  say_voice?: string;
  /** Language code for text-to-speech (e.g. "en-US"). */
  say_language?: string;
  /** Gender for text-to-speech. The `"male" | "female"` literals are autocompleted and typo-checked; any other string value is also accepted. */
  say_gender?: 'male' | 'female';
  /** If true, auto-answer the call before playing audio. Default true. */
  auto_answer?: boolean;
}

declare module './SwmlBuilder.js' {
  interface SwmlBuilder {
    /** Creates an AI agent that conducts voice conversations using automatic speech recognition (ASR), large language models (LLMs), and text-to-speech (TTS) synthesis. The agent processes caller speech in real-time, generates contextually appropriate responses, and can execute custom functions to interact with external systems through SignalWire AI Gateway (SWAIG). */
    ai(config?: AiVerbConfig): this;
    /** Start ai_sidecar mode — live_transcribe with an LLM/SWAIG/MCP loop on top. Without `lang`, the operation has no effect: it is accepted and ignored, not rejected. */
    ai_sidecar(config?: AiSidecarConfig | unknown[] | number | string): this;
    /** Creates a new Bedrock AI Agent */
    amazon_bedrock(config?: AmazonBedrockConfig | unknown[] | number | string): this;
    /** Answer incoming call and set an optional maximum duration. */
    answer(config?: AnswerConfig | unknown[] | number | string): this;
    /** Bind DTMF digit actions. */
    bind_digit(config?: BindDigitConfig): this;
    /** Clear all digit bindings. */
    clear_digit_bindings(config?: ClearDigitBindingsConfig): this;
    /** Body shape enforced by is_valid_cond_method, swml_schema.c:1271. */
    cond(config?: unknown[]): this;
    /** Dial a SIP URI or phone number. */
    connect(config?: ConnectConfig): this;
    /** Start noise reduction. You can stop it at any time using `stop_denoise`. */
    denoise(config?: Record<string, unknown> | unknown[] | number | string): this;
    /** A detection method that combines AMD (Answering Machine Detection) and fax detection. Detect whether the user on the other end of the call is a machine (fax, voicemail, etc.) or a human. The detection result(s) will be sent to the specified status_url as a POST request and will also be saved in the detect_result variable. */
    detect_machine(config?: DetectMachineConfig | unknown[] | number | string): this;
    /** Echo audio back to the caller. */
    echo(config?: EchoConfig | unknown[] | number | string): this;
    /** Place the current call in a named queue where it will wait to be connected to an available agent or resource. While waiting, callers will hear music or custom audio. When an agent connects to the queue (using the connect method), the caller and agent are bridged together. After the bridge completes, execution continues with the SWML script specified in transfer_after_bridge. */
    enter_queue(config?: EnterQueueConfig | unknown[] | number | string): this;
    /** Execute a specified section or URL as a subroutine, and upon completion, return to the current document. Use the return statement to pass any return values or objects back to the current document. */
    execute(config?: ExecuteConfig | unknown[] | number | string): this;
    /** Execute a remote procedure call. */
    execute_rpc(config?: ExecuteRpcConfig | unknown[] | number | string): this;
    /** Jump to a label, optionally based on a condition. The label is looked up in the current section first and then in each enclosing block, so a `goto` inside `switch`, `cond` or `execute.on_return` can target a label in the section that contains it. A section run with `execute` cannot jump back into its caller. */
    goto(config?: GotoConfig | unknown[] | number | string): this;
    /** End the call with an optional reason. */
    hangup(config?: HangupConfig | unknown[] | number | string): this;
    /** Join an ad-hoc audio conference. This method allows you to connect the current call to a named conference where multiple participants can communicate simultaneously. */
    join_conference(config?: JoinConferenceConfig | unknown[] | number | string): this;
    /** Join a RELAY room. If the room doesn't exist, it creates a new room. */
    join_room(config?: JoinRoomConfig | unknown[] | number | string): this;
    /** Mark any point of the SWML section with a label so that goto can jump to it. */
    label(config?: LabelConfig | unknown[] | number | string): this;
    /** Start live transcription of the call. The transcription will be sent to the specified webhook URL. Without `action`, the operation has no effect: it is accepted and ignored, not rejected. */
    live_transcribe(config?: LiveTranscribeConfig | unknown[] | number | string): this;
    /** Start live translation of the call. The translation will be sent to the specified webhook URL. Without `action`, the operation has no effect: it is accepted and ignored, not rejected. */
    live_translate(config?: LiveTranslateConfig | unknown[] | number | string): this;
    /** Enables secure payment processing during voice calls. When implemented, it manages the entire payment flow including data collection, validation, and processing through your configured payment gateway. */
    pay(config?: PayConfig | unknown[] | number | string): this;
    /** Play file(s), ringtones, speech or silence. */
    play(config?: PlayVerbConfig): this;
    /** Play a prompt and wait for input. The input can be received either as digits from the keypad, or from speech, or both depending on what parameters are set. By default, only digit input is enabled. To enable speech input, set at least one speech parameter. To enable both digit and speech input, set at least one parameter for each. */
    prompt(config?: PromptConfig | unknown[] | number | string): this;
    /** Receive a fax being delivered to this call. */
    receive_fax(config?: ReceiveFaxConfig | unknown[] | number | string): this;
    /** Record the call audio in the foreground, pausing further SWML execution until recording ends. Use this, for example, to record voicemails. To record calls in the background in a non-blocking fashion, use the record_call method. */
    record(config?: RecordConfig | unknown[] | number | string): this;
    /** Record call in the background. Unlike the record method, the record_call method will start the recording and continue executing the SWML script while allowing the recording to happen in the background. To stop call recordings started with record_call, use the stop_record_call method. */
    record_call(config?: RecordCallConfig | unknown[] | number | string): this;
    /** Send a GET, POST, PUT, or DELETE request to a remote URL. */
    request(config?: RequestConfig | unknown[] | number | string): this;
    /** Return a value from an execute call or exit the script. The value can be any type. */
    return(config?: Record<string, unknown> | unknown[] | boolean | number | string): this;
    /** Send 180 Ringing on an inbound call without answering. */
    ring(config?: Record<string, unknown> | unknown[] | number | string): this;
    /** Send SIP REFER to a SIP call. */
    sip_refer(config?: SipReferConfig | unknown[] | number | string): this;
    /** Send digit presses as DTMF tones. */
    send_digits(config?: SendDigitsConfig | unknown[] | number | string): this;
    /** Send a fax. */
    send_fax(config?: SendFaxConfig | unknown[] | number | string): this;
    /** Send an outbound SMS or MMS message to a PSTN phone number. */
    send_sms(config?: SendSmsConfig): this;
    /** Set script variables to the specified values. Accepts an object mapping variable names to values. Variables set using set can be removed using unset. */
    set(config?: Record<string, unknown>): this;
    /** Override subscriber capabilities */
    set_capabilities(config?: SetCapabilitiesConfig | unknown[] | number | string): this;
    /** Add customer metadata to call and conference events */
    set_meta(config?: SetMetaConfig | unknown[] | number | string): this;
    /** Pause execution for a specified duration. */
    sleep(durationOrConfig: number | { duration: number }): this;
    /** Stop noise reduction that was started with denoise. */
    stop_denoise(config?: Record<string, unknown> | unknown[] | number | string): this;
    /** Stop an active background recording. */
    stop_record_call(config?: StopRecordCallConfig | unknown[] | number | string): this;
    /** Stop streaming call audio. */
    stop_stream(config?: StopStreamConfig | unknown[] | number | string): this;
    /** Stop an active tap stream. */
    stop_tap(config?: StopTapConfig | unknown[] | number | string): this;
    /** Stream call audio to a WebSocket endpoint. */
    stream(config?: StreamConfig | unknown[] | number | string): this;
    /** Execute different instructions based on a variable's value. */
    switch(config?: SwitchConfig | unknown[] | number | string): this;
    /** Start background call tap. Media is streamed over Websocket or RTP to customer controlled URI. */
    tap(config?: TapConfig | unknown[] | number | string): this;
    /** Start transcription on the call. */
    transcribe(config?: TranscribeConfig | unknown[] | number | string): this;
    /** Stop transcription on the call. */
    transcribe_stop(config?: Record<string, unknown> | unknown[] | number | string): this;
    /** Transfer the execution of the script to a different SWML section, URL, or Relay application. Once the transfer is complete, the script will continue executing SWML from the new location. */
    transfer(config?: TransferConfig | unknown[] | number | string): this;
    /** validator: is_valid_swml_set_var_name */
    unset(config?: unknown[] | string): this;
    /** Allows the user to set and send events to the connected client on the call. This is useful for triggering actions on the client side. Commonly used with the [browser-sdk](https://developer.signalwire.com/sdks/reference/browser-sdk/SignalWire%20Client/). The event object can be any valid JSON object. Any key-value pair in the object is sent to the client as an event type called `user_event`. Without `event`, the operation has no effect: it is accepted and ignored, not rejected. */
    user_event(config?: UserEventConfig | unknown[] | number | string): this;
  }
}

export {};
