// AUTO-GENERATED from src/rest/namespaces/*.types.generated.ts — DO NOT EDIT.
// Regenerate with: npx tsx scripts/generate-public-types.ts
//
// The public re-export barrel for the REST wire & serialization DTOs — the
// generated `*Request`/`*Response` types every RestClient method takes and
// returns. Wired into src/rest/index.ts so they import from '@signalwire/sdk'.
// Cross-spec name collisions (same identifier, different shape in two specs)
// are namespace-prefixed; all other names are re-exported flat.

export type {
  CallAIMessageRequest,
  CallAIStopRequest,
  CallCollectRequest,
  CallCollectStartInputTimersRequest,
  CallCollectStopRequest,
  CallCreateRequest,
  CallDenoiseRequest,
  CallDenoiseStopRequest,
  CallDetectRequest,
  CallDetectStopRequest,
  CallDisconnectRequest,
  CallHangupRequest,
  CallHoldRequest,
  Request as CallingRequest,
  CallLiveTranscribeRequest,
  CallLiveTranslateRequest,
  CallPlayPauseRequest,
  CallPlayRequest,
  CallPlayResumeRequest,
  CallPlayStopRequest,
  CallPlayVolumeRequest,
  CallReceiveFaxStopRequest,
  CallRecordPauseRequest,
  CallRecordRequest,
  CallRecordResumeRequest,
  CallRecordStopRequest,
  CallReferRequest,
  CallRequest,
  CallResponse,
  CallSendFaxStopRequest,
  CallStreamRequest,
  CallStreamStopRequest,
  CallTapRequest,
  CallTapStopRequest,
  CallTranscribeRequest,
  CallTranscribeStopRequest,
  CallTransferRequest,
  CallUnholdRequest,
  CallUpdateCurrentCallRequest,
  CallUserEventRequest,
} from './namespaces/calling.types.generated.js';

export type {
  ChunkListResponse,
  ChunkPaginationResponse,
  ChunkResponse,
  DocumentCreatePageRequest,
  DocumentCreateParagraphRequest,
  DocumentCreateRequest,
  DocumentCreateSentenceRequest,
  DocumentCreateSlidingRequest,
  DocumentListResponse,
  DocumentSearchRequest,
  DocumentUpdateRequest,
  PaginationResponse,
  SearchResponse,
} from './namespaces/datasphere.types.generated.js';

export type {
  AIAddressPaginationResponse,
  AIAgentAddressListResponse,
  AIAgentCreateRequest,
  AIAgentListResponse,
  AIAgentPaginationResponse,
  AIAgentResponse,
  AIAgentUpdateRequest,
  CallFlowAddressListResponse,
  CallFlowAddressPaginationResponse,
  CallFlowCreateRequest,
  CallFlowListResponse,
  CallFlowResponse,
  CallFlowUpdateRequest,
  CallFlowVersionDeployRequest,
  CallFlowVersionDeployResponse,
  CallFlowVersionListResponse,
  CallFlowVersionsPaginationResponse,
  ConferenceRoomAddressListResponse,
  ConferenceRoomAddressPaginationResponse,
  ConferenceRoomCreateRequest,
  ConferenceRoomListResponse,
  ConferenceRoomResponse,
  ConferenceRoomUpdateRequest,
  CxmlApplicationAddressListResponse,
  CxmlApplicationAddressPaginationResponse,
  CxmlApplicationListResponse,
  CxmlApplicationPaginationResponse,
  CxmlApplicationResponse,
  CxmlApplicationUpdateRequest,
  CXMLScriptAddressListResponse,
  CXMLScriptAddressPaginationResponse,
  CXMLScriptCreateRequest,
  CXMLScriptListResponse,
  CXMLScriptResponse,
  CXMLScriptUpdateRequest,
  CXMLWebhookAddressListResponse,
  CXMLWebhookAddressPaginationResponse,
  CXMLWebhookCreateRequest,
  CXMLWebhookListResponse,
  CXMLWebhookPaginationResponse,
  CXMLWebhookResponse,
  CXMLWebhookUpdateRequest,
  DialogflowAgentAddressListResponse,
  DialogflowAgentAddressPaginationResponse,
  DialogflowAgentListResponse,
  DialogflowAgentResponse,
  DialogflowAgentUpdateRequest,
  DialogFlowPaginationResponse,
  DomainApplicationAssignRequest,
  EmbedsTokensRequest,
  EmbedsTokensResponse,
  FabricAddressesResponse,
  FabricAddressPaginationResponse,
  DomainApplicationResponse as FabricDomainApplicationResponse,
  Request as FabricRequest,
  SipEndpointListResponse as FabricSipEndpointListResponse,
  SipEndpointResponse as FabricSipEndpointResponse,
  FreeswitchConectorPaginationResponse,
  FreeswitchConnectorAddressListResponse,
  FreeswitchConnectorAddressPaginationResponse,
  FreeswitchConnectorCreateRequest,
  FreeswitchConnectorListResponse,
  FreeswitchConnectorResponse,
  FreeswitchConnectorUpdateRequest,
  ListSipEndpointsResponse,
  ListSubscriberAddressesResponse,
  ListSwmlScriptsResponse,
  PhoneRouteAssignRequest,
  PhoneRouteResponse,
  RelayApplicationAddressListResponse,
  RelayApplicationAddressPaginationResponse,
  RelayApplicationCreateRequest,
  RelayApplicationListResponse,
  RelayApplicationResponse,
  RelayApplicationUpdateRequest,
  ResourceAddressListResponse,
  ResourceAddressPaginationResponse,
  ResourceListResponse,
  ResourcePaginationResponse,
  ResourceResponse,
  ResourceSipEndpointAssignRequest,
  ResourceSipEndpointResponse,
  SipEndpointAddressListResponse,
  SipEndpointAddressPaginationResponse,
  SipEndpointCreateRequest,
  SipEndpointPaginationResponse,
  SipEndpointUpdateRequest,
  SipGatewayAddressListResponse,
  SipGatewayAddressPaginationResponse,
  SipGatewayListResponse,
  SipGatewayPaginationResponse,
  SipGatewayRequest,
  SipGatewayResponse,
  SubscriberAddressesResponse,
  SubscriberAddressPaginationResponse,
  SubscriberGuestTokenCreateRequest,
  SubscriberGuestTokenCreateResponse,
  SubscriberInviteTokenCreateRequest,
  SubscriberInviteTokenCreateResponse,
  SubscriberListResponse,
  SubscriberPaginationResponse,
  SubscriberRefreshTokenRequest,
  SubscriberRefreshTokenResponse,
  SubscriberRequest,
  SubscriberResponse,
  SubscriberSipEndpointListResponse,
  SubscriberSipEndpointPaginationResponse,
  SubscriberSipEndpointRequest,
  SubscriberTokenRequest,
  SubscriberTokenResponse,
  SWMLScriptAddressListResponse,
  SWMLScriptAddressPaginationResponse,
  SwmlScriptCreateRequest,
  SwmlScriptListResponse,
  SwmlScriptResponse,
  SwmlScriptUpdateRequest,
  SWMLWebhookAddressListResponse,
  SWMLWebhookAddressPaginationResponse,
  SWMLWebhookCreateRequest,
  SWMLWebhookListResponse,
  SWMLWebhookPaginationResponse,
  SWMLWebhookResponse,
  SWMLWebhookUpdateRequest,
} from './namespaces/fabric.types.generated.js';

export type {
  LogListResponse as FaxLogListResponse,
  LogPaginationResponse as FaxLogPaginationResponse,
  LogResponse,
} from './namespaces/fax.types.generated.js';

export type { ConferencesResponse } from './namespaces/logs.types.generated.js';

export type {
  LogRetrieveResponse,
  LogListResponse as MessageLogListResponse,
  LogPaginationResponse as MessageLogPaginationResponse,
} from './namespaces/message.types.generated.js';

export type {
  CreateMessageRequest,
  UpdateMessageRequest,
} from './namespaces/messages.types.generated.js';

export type {
  CreateTokenRequest,
  TokenResponse,
  UpdateTokenRequest,
} from './namespaces/project.types.generated.js';

export type {
  AddNumberGroupMembershipRequest,
  AddressListResponse,
  AddressResponse,
  AssignedNumberListResponse,
  AvailablePhoneNumbersResponse,
  BrandListResponse,
  BrandResponse,
  CampaignListResponse,
  CampaignResponse,
  CreateAddressRequest,
  CreateBrandRequest,
  CreateCampaignRequest,
  CreateCspBrandRequest,
  CreateDomainApplicationRequest,
  CreateManagedBrandRequest,
  CreateManagedCampaignRequest,
  CreateNumberGroupRequest,
  CreateOrderRequest,
  CreatePartnerCampaignRequest,
  CreateQueueRequest,
  CreateSipEndpointRequest,
  CreateVerifiedCallerIDRequest,
  DomainAppCallHandlerRequest,
  DomainApplicationListResponse,
  GetRecordingResponse,
  ImportPhoneNumberRequest,
  MfaRequest,
  MfaResponse,
  MfaVerifyRequest,
  MfaVerifyResponse,
  NumberGroupListResponse,
  NumberGroupMembershipListResponse,
  NumberGroupMembershipResponse,
  NumberGroupResponse,
  OrderListResponse,
  OrderResponse,
  PhoneNumberCallHandlerRequest,
  PhoneNumberListResponse,
  PhoneNumberLookupResponse,
  PhoneNumberResponse,
  PurchasePhoneNumberRequest,
  QueueListResponse,
  QueueMemberListResponse,
  QueueMemberResponse,
  QueueResponse,
  RecordingListResponse,
  DomainApplicationResponse as RelayRestDomainApplicationResponse,
  SipEndpointListResponse as RelayRestSipEndpointListResponse,
  SipEndpointResponse as RelayRestSipEndpointResponse,
  ShortCodeListResponse,
  ShortCodeResponse,
  SipProfileResponse,
  UpdateCampaignRequest,
  UpdateDomainApplicationRequest,
  UpdateNumberGroupRequest,
  UpdatePhoneNumberRequest,
  UpdateQueueRequest,
  UpdateShortCodeRequest,
  UpdateSipEndpointRequest,
  UpdateSipProfileRequest,
  UpdateVerifiedCallerIDRequest,
  VerifiedCallerIDListResponse,
  VerifiedCallerIDResponse,
  VerifyCallerIDRequest,
} from './namespaces/relay-rest.types.generated.js';

export type {
  CreateConferenceRequest,
  CreateRoomRequest,
  CreateRoomTokenRequest,
  CreateStreamRequest,
  ListConferencesResponse,
  ListConferenceTokensResponse,
  ListLogsResponse,
  ListRoomRecordingEventsResponse,
  ListRoomRecordingsResponse,
  ListRoomSessionEventsResponse,
  ListRoomSessionMembersResponse,
  ListRoomSessionRecordingsResponse,
  ListRoomSessionsResponse,
  ListRoomsResponse,
  ListStreamsResponse,
  RoomResponse,
  RoomTokenResponse,
  UpdateConferenceRequest,
  UpdateRoomRequest,
  UpdateStreamRequest,
} from './namespaces/video.types.generated.js';

export type {
  LogEventsListResponse,
  LogListResponse as VoiceLogListResponse,
  LogPaginationResponse as VoiceLogPaginationResponse,
} from './namespaces/voice.types.generated.js';
